
top: EchoTestTop.java EchoTest.java RS232C_RX_Wrapper.java RS232C_TX_Wrapper.java
	java -cp ../../bin:. synthesijer.Main EchoTest.java RS232C_RX_Wrapper.java RS232C_TX_Wrapper.java
	javac -cp ../../bin:. EchoTestTop.java
	java -cp ../../bin:. EchoTestTop
